### ISSUE TITLE
Upgrade to the latest version of spring-boot-starter-parent

### ISSUE THREAD

**Issue by maccac** [tyro/rabbit-amazon-bridge#20]
We are a couple or releases behind. We should get it up to date.

**Comment by maccac** [comment]
Updated the issue title as the spring platform BOM has been end of lifed. We should switch to the latest version of the spring-boot-starter-parent.

**Comment by maccac** [comment]
I've made an initial attempt at this over [in this branch](https://github.com/maccac/rabbit-amazon-bridge/tree/20_migrating_to_spring_boot_starter_parent). I want to do a bit more testing before submitting a pull requests.

**Comment by rpai-tyro** [comment]
Fixed by #46
