### ISSUE TITLE
Produce a docker image as well as a jar

### ISSUE THREAD

**Issue by maccac** [tyro/rabbit-amazon-bridge#23]
For ease of deployment we should look at producing a docker image. 
Once we have one, we can then consider pushing to docker hub as well as maven central

**Comment by pauldthomson** [comment]
This shouldn't be too hard either: https://docs.docker.com/docker-hub/builds/

**Comment by maccac** [comment]
That's a pretty cool idea. We should try it out once we have a dockerhub account sorted. I wonder if it can also be chained from a CI build.

**Comment by maccac** [comment]
Just realised that of course this will be fine because once we have a CI in place all merges will have gone through a build prior to a merge. How about we try this out after we've got one in place?

**Comment by mc-tyro** [comment]
@martingreber may want to take a look at this.

**Comment by maccac** [comment]
We are not producing a docker image at
- https://hub.docker.com/r/tyro/rabbit-amazon-brige/
- See #49
