### ISSUE TITLE
Add support for a custom property file or remove it

### ISSUE THREAD

**Issue by maccac** [tyro/rabbit-amazon-bridge#9]
We currently reference a `private.properties` file. This is something that we had to do for our application due our on-prem setup. If we can't change our on-prem setup and remove this property file we can look at making its path a configuration option.

**Comment by mc-tyro** [comment]
Changing our existing on prem behaviour will be difficult. As such we could allow the filename to be configurable as follows: 

```kotlin
@PropertySource(value = ["\${extra.properties.files}"], ignoreResourceNotFound = true)
```

This means we can add an additional property if we wish without forcing the naming convention of a private.properties file on others. If no additional property file is specified it will just be ignored. 

I would probably recommend that users stick with standard spring application-<profile>.properties files unless they have a specific use case like we did. 

Your thoughts @rajeshgpai?
